USE COBRA 

--03-MARZO-2020 18 min  


/****************************************************************************************************************************************/
PRINT '/**********  INICIO DE SCRIPT 07_GENERANDO_ASIGNACION_AVANZADA  **********\'
PRINT 'HORA INICIO: ' + cast(cast(getdate() as dateTIME) as varchar(20))
/****************************************************************************************************************************************/

--16	SERVEX
--20	RJ PREMIUM
--8	CLASA AVANZADA
--10	RJ
--18	EXCLUSION AVANZADA

go
--- UNIVERSO AVANZADA --- 
DROP TABLE #JAS_UNIVERSO_AVANZADA
go
SELECT * INTO #JAS_UNIVERSO_AVANZADA FROM SRMS.DBO.JAS_BASE_SERVICIOS_LUNA_ASIGNACION 
WHERE MARCA_FECHA_BAJA=0 OR (MARCA_FECHA_BAJA BETWEEN 1 AND 12 AND FLAG_DEUDA=1)  --- BASE FINAL A DISTRIBUIR ---
go
--- 
ALTER TABLE #JAS_UNIVERSO_AVANZADA ADD COD_AGENCIA_AVANZADA TINYINT
go
---- ASIGNANDO RJ PREMIUM ---
UPDATE #JAS_UNIVERSO_AVANZADA
SET COD_AGENCIA_AVANZADA=20
WHERE COD_SEGMENTO=4
AND COD_AGENCIA_AVANZADA IS NULL
go
---- EXCLUSION AVANZADA 

DROP TABLE #JAS_BASE_EXLUSION
go
SELECT DISTINCT COD_LUNA 
INTO #JAS_BASE_EXLUSION
FROM cobra.LUNA.DATA_IND_EXCLUSION_JAS
go
UPDATE #JAS_UNIVERSO_AVANZADA
SET COD_AGENCIA_AVANZADA=18
FROM #JAS_UNIVERSO_AVANZADA A
JOIN #JAS_BASE_EXLUSION B
ON A.COD_LUNA=B.COD_LUNA
WHERE A.COD_AGENCIA_AVANZADA IS NULL
go
--- MARCANDO AGENCIAS SERVEX 16 / RJ 10  / CLASA 8
DROP TABLE #JAS_AGENCIAS_AVANZADA_INI_0
go
SELECT DISTINCT COD_LUNA,ISNULL(COD_COMPORTAMIENTO_MERCADO,0) COD_COMPORTAMIENTO_MERCADO,ISNULL(COD_RANGO_DEUDA_AVANZADA,0) COD_RANGO_DEUDA_AVANZADA,
CASE 
	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0)=0 THEN 0
	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0) BETWEEN 5 AND 7 THEN 1
	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0) >7 THEN 2
END COD_RANGO_DEUDA_AVANZADA_AGRUP
INTO #JAS_AGENCIAS_AVANZADA_INI_0
FROM #JAS_UNIVERSO_AVANZADA WHERE COD_AGENCIA_AVANZADA IS NULL

go
---------------- AGENCIA ANTERIOR 
DROP TABLE #JAS_AGENCIA_TEM_ANTERIOR_AV

go

SELECT DISTINCT COD_LUNA,COD_AGENCIA 
INTO #JAS_AGENCIA_TEM_ANTERIOR_AV 
FROM srms.dbo.JAS_MASTER_AGENCIA_ASIGNADA_BK_LUNA 
WHERE COD_GESTION=2 AND 
COD_AGENCIA IN (16,10,8)

go
----- MARCA AG ANT
ALTER TABLE #JAS_AGENCIAS_AVANZADA_INI_0 ADD MARCA_ASIGNACION_ANTERIOR TINYINT
go

UPDATE #JAS_AGENCIAS_AVANZADA_INI_0
SET MARCA_ASIGNACION_ANTERIOR=1
FROM #JAS_AGENCIAS_AVANZADA_INI_0 A
JOIN #JAS_AGENCIA_TEM_ANTERIOR_AV B
ON A.COD_LUNA=B.COD_LUNA
go
--- CUENTAS A DISTRIBUIR ----
---- #JAS_AGENCIAS_AVANZADA
DROP TABLE #JAS_AGENCIAS_AVANZADA
go
SELECT DISTINCT COD_LUNA,COD_COMPORTAMIENTO_MERCADO,COD_RANGO_DEUDA_AVANZADA,COD_RANGO_DEUDA_AVANZADA_AGRUP
INTO #JAS_AGENCIAS_AVANZADA
FROM #JAS_AGENCIAS_AVANZADA_INI_0 WHERE MARCA_ASIGNACION_ANTERIOR IS NULL

--- AGENCIA ANTERIOR 
go
ALTER TABLE #JAS_AGENCIAS_AVANZADA ADD COD_AGENCIA_ANTERIOR TINYINT
go
---SELECT * FROM #JAS_AGENCIAS_AVANZADA

UPDATE #JAS_AGENCIAS_AVANZADA
SET COD_AGENCIA_ANTERIOR=B.COD_AGENCIA
FROM #JAS_AGENCIAS_AVANZADA A
JOIN #JAS_AGENCIA_TEM_ANTERIOR_AV B
ON A.COD_LUNA=B.COD_LUNA
go
ALTER TABLE #JAS_AGENCIAS_AVANZADA ADD cod_agencia_tmp TINYINT,cod_agencia2 TINYINT

go
update #JAS_AGENCIAS_AVANZADA 
set cod_agencia_tmp=
CASE
	WHEN COD_AGENCIA_ANTERIOR=8 THEN  1
	WHEN COD_AGENCIA_ANTERIOR IS NULL THEN  2
	WHEN COD_AGENCIA_ANTERIOR=10 THEN  3
	WHEN COD_AGENCIA_ANTERIOR=16 THEN  4
END 

go
drop table #tmp_distribucion 
go

select *,row_number() over(partition by COD_COMPORTAMIENTO_MERCADO,COD_RANGO_DEUDA_AVANZADA_AGRUP order by cod_Agencia_tmp asc) orden 
into #tmp_distribucion
from #JAS_AGENCIAS_AVANZADA where cod_agencia2 is null

go

update #tmp_distribucion 
set cod_agencia2=8
from #tmp_distribucion a join 
(select COD_COMPORTAMIENTO_MERCADO,COD_RANGO_DEUDA_AVANZADA_AGRUP,count(1) ctd,count(1)/3 ctd_reg from #tmp_distribucion 
group by COD_COMPORTAMIENTO_MERCADO,COD_RANGO_DEUDA_AVANZADA_AGRUP) b 
on a.COD_comportamiento_mercado=b.COD_comportamiento_mercado AND A.COD_RANGO_DEUDA_AVANZADA_AGRUP=B.COD_RANGO_DEUDA_AVANZADA_AGRUP
where a.orden<=b.ctd_reg and a.cod_agencia2 is null


go

update #tmp_distribucion 
set cod_agencia_tmp=
CASE
	WHEN COD_AGENCIA_ANTERIOR=16 THEN  1
	WHEN COD_AGENCIA_ANTERIOR IS NULL THEN  2
	WHEN COD_AGENCIA_ANTERIOR=10 THEN  3
	WHEN COD_AGENCIA_ANTERIOR=8 THEN  4
END 

go

drop table #tmp_distribucion2
go
select *,row_number() over(partition by COD_COMPORTAMIENTO_MERCADO,COD_RANGO_DEUDA_AVANZADA_AGRUP order by cod_Agencia_tmp asc) orden2 
into #tmp_distribucion2
from #tmp_distribucion where cod_agencia2 is null
go
alter table #tmp_distribucion add orden2 int
go
update #tmp_distribucion
set orden2=b.orden2
from #tmp_distribucion a
join #tmp_distribucion2 b on a.COD_LUNA=b.COD_LUNA

go

update #tmp_distribucion 
set cod_agencia2=16
from #tmp_distribucion a join 
(select COD_COMPORTAMIENTO_MERCADO,COD_RANGO_DEUDA_AVANZADA_AGRUP,count(1) ctd,count(1)/2 ctd_reg 
from #tmp_distribucion2 group by COD_COMPORTAMIENTO_MERCADO,COD_RANGO_DEUDA_AVANZADA_AGRUP) b 
on a.COD_comportamiento_mercado=b.COD_comportamiento_mercado AND A.COD_RANGO_DEUDA_AVANZADA_AGRUP=B.COD_RANGO_DEUDA_AVANZADA_AGRUP
where a.orden2<=b.ctd_reg and a.cod_agencia2 is null
--- 1851255
go
update #tmp_distribucion 
set cod_agencia2=10
from #tmp_distribucion a 
where a.cod_agencia2 is null

go
---
UPDATE #JAS_UNIVERSO_AVANZADA
SET COD_AGENCIA_AVANZADA=B.COD_AGENCIA2
FROM #JAS_UNIVERSO_AVANZADA A
JOIN #tmp_distribucion B
ON A.COD_LUNA=B.COD_LUNA
WHERE A.COD_AGENCIA_AVANZADA IS NULL

------------------------
go
----- MARCANDO EL UNIVERSO DE TEMPRANA -----
---SELECT * FROM srms.dbo.JAS_MASTER_AGENCIA_ASIGNADA_BK_LUNA
DROP TABLE #JAS_ASIGNACION_ANTERIOR_LUNA_AV
go
SELECT * 
INTO #JAS_ASIGNACION_ANTERIOR_LUNA_AV
FROM srms.dbo.JAS_MASTER_AGENCIA_ASIGNADA_BK_LUNA 
WHERE COD_GESTION=2 ---- GESTION TEMPRANA 
go
ALTER TABLE #JAS_UNIVERSO_AVANZADA ADD FECHA_ASIGNACION DATE,MARCA_ASIGNACION BIT
go
UPDATE #JAS_UNIVERSO_AVANZADA
SET 
COD_AGENCIA_AVANZADA=B.COD_AGENCIA
FROM #JAS_UNIVERSO_AVANZADA A
JOIN #JAS_ASIGNACION_ANTERIOR_LUNA_AV B ON A.COD_LUNA=B.COD_LUNA
WHERE A.COD_AGENCIA_AVANZADA IS NULL

go

UPDATE #JAS_UNIVERSO_AVANZADA
SET 
FECHA_ASIGNACION=CASE WHEN B.COD_LUNA IS NOT NULL AND ISNULL(A.COD_AGENCIA_AVANZADA,99)=B.COD_AGENCIA THEN B.FECHA_ASIGNACION ELSE CONVERT(DATE,GETDATE(),121) END ,
MARCA_ASIGNACION=CASE WHEN B.COD_LUNA IS NOT NULL AND ISNULL(A.COD_AGENCIA_AVANZADA,99)=B.COD_AGENCIA THEN 0 ELSE 1 END
FROM #JAS_UNIVERSO_AVANZADA A
LEFT JOIN #JAS_ASIGNACION_ANTERIOR_LUNA_AV B ON A.COD_LUNA=B.COD_LUNA

go

------------------------ TABLAS FINALES ----

DROP TABLE SRMS.DBO.JAS_UNIVERSO_AVANZADA
go

SELECT * 
INTO SRMS.DBO.JAS_UNIVERSO_AVANZADA
FROM #JAS_UNIVERSO_AVANZADA
go
DROP TABLE SRMS.DBO.JAS_DIST_AVANZADA
go
SELECT *,COD_AGENCIA2 COD_AGENCIA_AVANZADA
INTO SRMS.DBO.JAS_DIST_AVANZADA
FROM #tmp_distribucion

go
---------------------------------------

--SELECT COD_AGENCIA_AVANZADA,ISNULL(COD_COMPORTAMIENTO_MERCADO,0) COD_COMPORTAMIENTO_MERCADO,ISNULL(COD_RANGO_DEUDA_AVANZADA,0) COD_RANGO_DEUDA_AVANZADA,
--CASE 
--	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0)=0 THEN 0
--	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0) BETWEEN 5 AND 7 THEN 1
--	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0) >7 THEN 2
--END COD_RANGO_DEUDA_AVANZADA_AGRUP,
--COUNT(DISTINCT COD_LUNA) FROM #JAS_UNIVERSO_AVANZADA
--GROUP BY COD_AGENCIA_AVANZADA,ISNULL(COD_COMPORTAMIENTO_MERCADO,0),ISNULL(COD_RANGO_DEUDA_AVANZADA,0),
--CASE 
--	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0)=0 THEN 0
--	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0) BETWEEN 5 AND 7 THEN 1
--	WHEN  ISNULL(COD_RANGO_DEUDA_AVANZADA,0) >7 THEN 2
--END

/****************************************************************************************************************************************/
PRINT 'HORA FIN: ' + cast(cast(getdate() as dateTIME) as varchar(20))
PRINT '\**********  FIN DE SCRIPT 07_GENERANDO_ASIGNACION_AVANZADA  **********/'
/****************************************************************************************************************************************/