USE COBRA
--03-MARZO-2020   6 Horas 18 MIN   
/****************************************************************************************************************************************/
PRINT '/**********  INICIO DE SCRIPT 04_PASOS_UPDATE_MODELO_LUNA_01  **********\'
PRINT 'HORA INICIO: ' + cast(cast(getdate() as dateTIME) as varchar(20))
/****************************************************************************************************************************************/
go
---2 en cobra
drop table [LUNA].[DATA_DIRECCIONES_AMDOCS]
go
select * into [LUNA].[DATA_DIRECCIONES_AMDOCS] from [LUNA].[DATA_DIRECCION_AMDOCS]

--3  cobra.[LUNA].[DATA_DIRECCIONES_AMDOCS] sirve para actualiar zonales en master_luna

go
--PASO0:	--OK 1 MIN  28-04
EXEC TERRA.SP_ACTUALIZA_PLANTAS_RUCs_POR_DNIs
go

--PASO1:	--OK 45.50 MIN Jueves 28-04
EXEC TERRA.SP_LOAD_MASTER_BASE		--40395930
go
EXEC TERRA.SP_LOAD_MASTER_TERRA		--40395930
go
EXEC TERRA.SP_RUN_SEGMENTACION		--31818321
go
--PASO2:	--OK 38 MIN  28-04
EXEC LUNA.SP_LOAD_MASTER_LUNA	
go		
EXEC LUNA.SP_LOAD_MASTER_CLIENTE_ATIS	
go
EXEC LUNA.SP_LOAD_MASTER_CLIENTE_CMS	
go
--EXEC LUNA.SP_LOAD_MASTER_CLIENTE_STC
--go
EXEC [LUNA].[SP_LOAD_MASTER_CLIENTE_AMDOCS]
----
--SP_LOAD_MASTER_LUNA EXECUTED SUCCESSFULLY
--SP_LOAD_MASTER_CLIENTE_ATIS EXECUTED SUCCESSFULLY AT Feb 12 2018  1:10PM
--SP_LOAD_MASTER_CLIENTE_CMS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:20PM
--SP_LOAD_MASTER_CLIENTE_STC EXECUTED SUCCESSFULLY AT Mar 12 2018  5:30PM
--SP_LOAD_MASTER_CLIENTE_AMDOCS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:32PM

go
	
EXEC LUNA.SP_LOAD_MASTER_CUENTA_ATIS	
go
EXEC LUNA.SP_LOAD_MASTER_CUENTA_CMS		
--go
--EXEC LUNA.SP_LOAD_MASTER_CUENTA_STC	
go
EXEC [LUNA].[SP_LOAD_MASTER_CUENTA_AMDOCS]
--
--SP_LOAD_MASTER_CUENTA_ATIS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:32PM
--SP_LOAD_MASTER_CUENTA_CMS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:33PM
--SP_LOAD_MASTER_CUENTA_STC EXECUTED SUCCESSFULLY AT Mar 12 2018  5:35PM

----
	go
EXEC LUNA.SP_LOAD_MASTER_SERVICIO_ATIS	
GO
EXEC LUNA.SP_LOAD_MASTER_SERVICIO_CMS	
GO
--EXEC LUNA.SP_LOAD_MASTER_SERVICIO_STC	
--GO
EXEC LUNA.SP_LOAD_MASTER_SERVICIO_AMDOCS
--------
go

--SP_LOAD_MASTER_CUENTA_AMDOCS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:36PM
--SP_LOAD_MASTER_SERVICIO_ATIS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:37PM
--SP_LOAD_MASTER_SERVICIO_CMS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:37PM
--SP_LOAD_MASTER_SERVICIO_STC EXECUTED SUCCESSFULLY AT Mar 12 2018  5:42PM
--SP_LOAD_MASTER_SERVICIO_AMDOCS EXECUTED SUCCESSFULLY AT Mar 12 2018  5:43PM



--select cod_sistema,count(1) from cobra.luna.MASTER_cliente
--group by cod_sistema

--select cod_sistema,count(1) from cobra.luna.MASTER_cuenta
--group by cod_sistema

--select cod_sistema,count(1) from cobra.luna.MASTER_SERVICIO
--group by cod_sistema


--SP_LOAD_MASTER_LUNA EXECUTED SUCCESSFULLY
--SP_LOAD_MASTER_CLIENTE_ATIS EXECUTED SUCCESSFULLY AT Apr 28 2017 11:44AM
--SP_LOAD_MASTER_CLIENTE_CMS EXECUTED SUCCESSFULLY AT Apr 28 2017 11:49AM
--SP_LOAD_MASTER_CLIENTE_STC EXECUTED SUCCESSFULLY AT Apr 28 2017 12:02PM
--SP_LOAD_MASTER_CUENTA_ATIS EXECUTED SUCCESSFULLY AT Apr 28 2017 12:03PM
--SP_LOAD_MASTER_CUENTA_CMS EXECUTED SUCCESSFULLY AT Apr 28 2017 12:03PM
--SP_LOAD_MASTER_CUENTA_STC EXECUTED SUCCESSFULLY AT Apr 28 2017 12:07PM
--SP_LOAD_MASTER_SERVICIO_ATIS EXECUTED SUCCESSFULLY AT Apr 28 2017 12:08PM
--SP_LOAD_MASTER_SERVICIO_CMS EXECUTED SUCCESSFULLY AT Apr 28 2017 12:09PM
--SP_LOAD_MASTER_SERVICIO_STC EXECUTED SUCCESSFULLY AT Apr 28 2017 12:13PM

--- HASTA AQUÍ LLEGUE
--EXEC LUNA.SP_LOAD_TRAN_DEUDA_ATIS
--EXEC LUNA.SP_LOAD_TRAN_DEUDA_CMS
--EXEC LUNA.SP_LOAD_TRAN_DEUDA_STC
--EXEC LUNA.SP_LOAD_TRAN_DEUDA_AMDOCS

--SP_LOAD_MASTER_CLIENTE_ATIS EXECUTED SUCCESSFULLY AT Feb 12 2018  1:10PM
--SP_LOAD_MASTER_CLIENTE_CMS EXECUTED SUCCESSFULLY AT Feb 12 2018  1:14PM
--SP_LOAD_MASTER_CLIENTE_STC EXECUTED SUCCESSFULLY AT Feb 12 2018  1:23PM
--SP_LOAD_MASTER_CLIENTE_AMDOCS EXECUTED SUCCESSFULLY AT Feb 12 2018  1:25PM

--XXX
EXEC [LUNA].[SP_RUN_CONVERGENCIA]		--OK  17 MIN	28-04
--SP_RUN_CONVERGENCIA Mar 12 2018  6:34PM 6974756 CONTEO DE SERVICIOS
--SP_RUN_CONVERGENCIA Mar 12 2018  6:36PM 6974756 ACTUALIZACION DEL CONTEO SERVICIOS
--SP_RUN_CONVERGENCIA Mar 12 2018  6:38PM 7239569 IDENTIFICACION DE CUENTAS CON DEUDA ACTIVA
--SP_RUN_CONVERGENCIA Mar 12 2018  6:38PM 6144293 CONTEO DE CUENTAS
--SP_RUN_CONVERGENCIA Mar 12 2018  6:39PM 6144293 ACTUALIZACION DEL CONTEO CUENTAS
--SP_RUN_CONVERGENCIA Mar 12 2018  6:39PM 5274586 CONTEO DE CLIENTES
--SP_RUN_CONVERGENCIA Mar 12 2018  6:40PM 5274586 ACTUALIZACION DEL CONTEO CLIENTES
--SP_RUN_CONVERGENCIA Mar 12 2018  6:40PM 5274586 CONTEO DE SISTEMAS
--SP_RUN_CONVERGENCIA Mar 12 2018  6:41PM 5274586 ACTUALIZACION DEL CONTEO SISTEMAS
--SP_RUN_CONVERGENCIA Mar 12 2018  6:42PM 5270066 RESET CONVERGENCIA
--SP_RUN_CONVERGENCIA Mar 12 2018  6:43PM 4158781 ASIGNACION CONVERGENCIA MONO
--SP_RUN_CONVERGENCIA Mar 12 2018  6:44PM 334516 ASIGNACION CONVERGENCIA DE UN SISTEMA UN CLIENTE Y VARIAS CUENTAS
--SP_RUN_CONVERGENCIA Mar 12 2018  6:44PM 146937 ASIGNACION CONVERGENCIA DE UN SISTEMA VARIOS CLIENTES
--SP_RUN_CONVERGENCIA Mar 12 2018  6:44PM 46670 ASIGNACION CONVERGENCIA MULTIPLE 7 
--SP_RUN_CONVERGENCIA Mar 12 2018  6:44PM 509996 ASIGNACION CONVERGENCIA MULTIPLE 8
--SP_RUN_CONVERGENCIA Mar 12 2018  6:44PM 56675 ASIGNACION CONVERGENCIA MULTIPLE 9
--SP_RUN_CONVERGENCIA Mar 12 2018  6:44PM 21011 ASIGNACION CONVERGENCIA MULTIPLE 10

go
--OK 21MIN 28-04

EXEC [LUNA].[SP_RUN_RANGO_DEUDA]				
---
go
EXEC [LUNA].[SP_LOAD_SCORE]						
go
EXEC [LUNA].[SP_LOAD_RIESGO]					
go
EXEC [LUNA].[SP_RUN_SCORE_CONVERGENTE_MONO]		------- akí me quedé falta convergente hacia abajo  --- 
go
-- OK	1min 28-04
EXEC [LUNA].[SP_RUN_SCORE_CONVERGENTE] -- – cambio orden de ejecución (antes estaba en la parte final)
go
--CORREGIR
--(4330729 row(s) affected)
--(4782618 row(s) affected)


-----------------------------------AGREGADO POR JAS ----------------------------------
EXEC LUNA.SP_ACTUALIZACION_BASE_EXCLUSION_JAS
-----------------------------------------------------------------------------------
---- tener presente este paso ---
go
EXEC LUNA.SP_RUN_INDICADOR 18

---- tener presente este paso ---

go
EXEC LUNA.SP_RANGO_DEUDA_90

go
/****************************************************************************************************************************************/
PRINT 'HORA FIN: ' + cast(cast(getdate() as dateTIME) as varchar(20))
PRINT '\**********  FIN DE SCRIPT 04_PASOS_UPDATE_MODELO_LUNA_01  **********/'
/****************************************************************************************************************************************/