GO
create PROC [dbo].[SP_RANGOSDEMORA]
AS
 SET NOCOUNT ON
select CAST(AMD.FECHA_EMISION AS date) AS FECHA_EMISION
		,CAST(AMD.FECHA_VENCIM AS date) AS FECHA_VENCIM
		,CAST(AMD.FECHA_DEUDA AS date) AS  FECHA_DEUDA
		,YEAR(AMD.FECHA_EMISION) AS PERIODO_EMISION
	    ,MONTH(AMD.FECHA_EMISION) AS MES_EMISION
	    ,YEAR(AMD.FECHA_VENCIM) AS PERIODO_VECIMIENTO
	    ,MONTH(AMD.FECHA_VENCIM) AS MES_VENCIMIENTO
		,DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) AS DIAS_ATRASO
		,CASE
			WHEN DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) <= 0  THEN 'POR VENCER'
			WHEN DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) <= 25 THEN '01-30'
			WHEN DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) <= 55 THEN '31-60'
			WHEN DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) <= 86 THEN '61-90'
			WHEN DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) <= 115 THEN '91-120'
			
			ELSE '121-MAS'
		 END AS RANGO_ATRASO,
		CASE
			WHEN DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) >= DP.VALORENTERO  THEN 'ANTIGUOS'
			WHEN DATEDIFF(DAY,AMD.FECHA_VENCIM,GETDATE()) <= DP.VALORENTERO THEN 'NUEVOS'
			END AS TIPO_ATRASO
		from DIN_DEUDA_AMDOCS AMD INNER JOIN DIN_MAE_PARAMETROS DP ON
		AMD.MAE_PARAMETROS_ID=DP.MAE_PARAMETROS_ID 
		WHERE  DP.MAE_PARAMETROS_ID=1 