USE [COBRA]
GO
/****** Object:  StoredProcedure [dbo].[SP_Riesgo_Score_Convergente_Cargar_y_Ejecutar_Proceso]    Script Date: 11/08/2020 12:14:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER Procedure [dbo].[SP_Riesgo_Score_Convergente_Cargar_y_Ejecutar_Proceso]
As

Begin

--LIMPAR EL LOG.
--================================================================
-- Modificar el modo de Recuperacion (Recovery) a nodo SIMPLE:
	ALTER DATABASE COBRA 
	SET RECOVERY SIMPLE

-- Reducir el archivo log a 1 MB.
	DBCC SHRINKFILE (COBRA_log1,1);

	DBCC SHRINKFILE('COBRA_log1', 0, TRUNCATEONLY)

-- Revertimos el nivel de Recovery a FULL
	ALTER DATABASE COBRA 
	SET RECOVERY FULL


--------------------------------------------------------------------------------
----------------------- CARGAR PLANTA EXPORTADA DEL 1212 -----------------------
--------------------------------------------------------------------------------

--truncate table [dbo].[Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm]
truncate table [dbo].[Riesgo_ScoreConv_Contactos_Fij_Mov_Tmmm]
truncate table [dbo].[Riesgo_ScoreConv_Sal_Mov]
truncate table [dbo].[Riesgo_ScoreConv_Fact_Mov]    ----5,237,616  -- xxxxx30
truncate table [dbo].[Riesgo_ScoreConv_Fact_Fij]
truncate table [dbo].[Riesgo_ScoreConv_Fact_Tmm]

--------------------------------------------------------------------------------
----------------------- CARGAR PLANTA EXPORTADA DEL 1005 -----------------------
--------------------------------------------------------------------------------

BULK INSERT [dbo].[Riesgo_ScoreConv_Contactos_Fij_Mov_Tmmm]--_temp  --
  FROM '\\gppesplcli1212\servidor_FACO\operaciones\DESA\GESTORES\MOVIL\Pagos\HOY\Riesgo_ScoreConv_Contactos_Fij_Mov_Tmmm.txt'
  WITH       (        FIELDTERMINATOR = '|', ROWTERMINATOR = '\n'     )
      
BULK INSERT [dbo].[Riesgo_ScoreConv_Sal_Mov]--_temp  --
  FROM '\\gppesplcli1212\servidor_FACO\operaciones\DESA\GESTORES\MOVIL\Pagos\HOY\Riesgo_ScoreConv_Sal_Mov.txt'
  WITH       (        FIELDTERMINATOR = '|', ROWTERMINATOR = '\n'     )
  
BULK INSERT [dbo].[Riesgo_ScoreConv_Fact_Mov]--_temp  --
  FROM '\\gppesplcli1212\servidor_FACO\operaciones\DESA\GESTORES\MOVIL\Pagos\HOY\Riesgo_ScoreConv_Fact_Mov.txt'
  WITH       (        FIELDTERMINATOR = '|', ROWTERMINATOR = '\n'     )
  
BULK INSERT [dbo].[Riesgo_ScoreConv_Fact_Fij]--_temp  --
  FROM '\\gppesplcli1212\servidor_FACO\operaciones\DESA\GESTORES\MOVIL\Pagos\HOY\Riesgo_ScoreConv_Fact_Fij.txt'
  WITH       (        FIELDTERMINATOR = '|', ROWTERMINATOR = '\n'     )
  
BULK INSERT [dbo].[Riesgo_ScoreConv_Fact_Tmm]--_temp  --
  FROM '\\gppesplcli1212\servidor_FACO\operaciones\DESA\GESTORES\MOVIL\Pagos\HOY\Riesgo_ScoreConv_Fact_Tmm.txt'
  WITH       (        FIELDTERMINATOR = '|', ROWTERMINATOR = '\n'     )   
    
	
 --------------------------------------------------------------------------------------------------------------------------
 -----------------------------------------------------PROCEDIMIENTO ------------------------------------------------------
 --------------------------------------------------------------------------------------------------------------------------

If OBJECT_ID('cobra.dbo.Riesgo_ScoreConv') Is Not Null Drop table  cobra.dbo.Riesgo_ScoreConv
--DROP TABLE cobra.dbo.Riesgo_ScoreConv

SELECT NRO_IDENTIFICACION AS NRO_IDENTIFICACION_ORIGEN , COD_TIPO_IDENTIFICACION AS TIP_DOC, RIGHT('000000000000000'+LTRIM(RTRIM(NRO_IDENTIFICACION)),15) AS DOC, COD_SEGMENTO AS SEG, 
MIN(MAX_FECHA_ALTA) AS MAX_FEC_ALTA
INTO cobra.dbo.Riesgo_ScoreConv
FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm
GROUP BY NRO_IDENTIFICACION, COD_TIPO_IDENTIFICACION, RIGHT('000000000000000'+LTRIM(RTRIM(NRO_IDENTIFICACION)),15), COD_SEGMENTO


ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
ANTIG INT


UPDATE cobra.dbo.Riesgo_ScoreConv
SET ANTIG = CASE WHEN MAX_FEC_ALTA IS NULL THEN NULL ELSE DATEDIFF(MONTH,MAX_FEC_ALTA,GETDATE()) END
FROM cobra.dbo.Riesgo_ScoreConv A


ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
FACT1_SUM_TF NUMERIC(15,2),
FACT2_SUM_TF NUMERIC(15,2),
FACT3_SUM_TF NUMERIC(15,2),
FACT4_SUM_TF NUMERIC(15,2),
FACT5_SUM_TF NUMERIC(15,2),
FACT6_SUM_TF NUMERIC(15,2),
FACT1_Q_TF INT,
FACT2_Q_TF INT,
FACT3_Q_TF INT,
FACT4_Q_TF INT,
FACT5_Q_TF INT,
FACT6_Q_TF INT,
FACT1_SUM_TM NUMERIC(15,2),
FACT2_SUM_TM NUMERIC(15,2),
FACT3_SUM_TM NUMERIC(15,2),
FACT4_SUM_TM NUMERIC(15,2),
FACT5_SUM_TM NUMERIC(15,2),
FACT6_SUM_TM NUMERIC(15,2),
FACT1_Q_TM INT,
FACT2_Q_TM INT,
FACT3_Q_TM INT,
FACT4_Q_TM INT,
FACT5_Q_TM INT,
FACT6_Q_TM INT,
FACT1_SUM_CABLE NUMERIC(15,2),
FACT2_SUM_CABLE NUMERIC(15,2),
FACT3_SUM_CABLE NUMERIC(15,2),
FACT4_SUM_CABLE NUMERIC(15,2),
FACT5_SUM_CABLE NUMERIC(15,2),
FACT6_SUM_CABLE NUMERIC(15,2),
FACT1_Q_CABLE INT,
FACT2_Q_CABLE INT,
FACT3_Q_CABLE INT,
FACT4_Q_CABLE INT,
FACT5_Q_CABLE INT,
FACT6_Q_CABLE INT



ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
DPAGO1_PROM_TF NUMERIC(15,2),
DPAGO2_PROM_TF NUMERIC(15,2),
DPAGO3_PROM_TF NUMERIC(15,2),
DPAGO4_PROM_TF NUMERIC(15,2),
DPAGO5_PROM_TF NUMERIC(15,2),
DPAGO6_PROM_TF NUMERIC(15,2),
DPAGO1_MAX_TF NUMERIC(15,2),
DPAGO1_PROM_TM NUMERIC(15,2),
DPAGO2_PROM_TM NUMERIC(15,2),
DPAGO3_PROM_TM NUMERIC(15,2),
DPAGO4_PROM_TM NUMERIC(15,2),
DPAGO5_PROM_TM NUMERIC(15,2),
DPAGO6_PROM_TM NUMERIC(15,2),
DPAGO1_MAX_TM NUMERIC(15,2),
DPAGO1_PROM_CABLE NUMERIC(15,2),
DPAGO2_PROM_CABLE NUMERIC(15,2),
DPAGO3_PROM_CABLE NUMERIC(15,2),
DPAGO4_PROM_CABLE NUMERIC(15,2),
DPAGO5_PROM_CABLE NUMERIC(15,2),
DPAGO6_PROM_CABLE NUMERIC(15,2),
DPAGO1_MAX_CABLE NUMERIC(15,2)



UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT1_SUM_TF = ISNULL(Q.FACT,0),
FACT1_Q_TF = ISNULL(Q.FACT_Q,0),
DPAGO1_PROM_TF = DPAGO,
DPAGO1_MAX_TF = DPAGO_MAX
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) <= 30 
           AND Fecha_Pago_1 IS NULL THEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) 
           WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO,
           MAX(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) <= 30 AND Fecha_Pago_1 IS NULL THEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) 
           WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END) AS DPAGO_MAX
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN  cobra.dbo.Riesgo_ScoreConv_Fact_Fij B			
           ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  0
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			
ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT2_SUM_TF = ISNULL(Q.FACT,0),
FACT2_Q_TF = ISNULL(Q.FACT_Q,0),
DPAGO2_PROM_TF = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Fij B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  1
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT3_SUM_TF = ISNULL(Q.FACT,0),
FACT3_Q_TF = ISNULL(Q.FACT_Q,0),
DPAGO3_PROM_TF = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Fij B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) = 2
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT4_SUM_TF = ISNULL(Q.FACT,0),
FACT4_Q_TF = ISNULL(Q.FACT_Q,0),
DPAGO4_PROM_TF = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Fij B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  3 
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT5_SUM_TF = ISNULL(Q.FACT,0),
FACT5_Q_TF = ISNULL(Q.FACT_Q,0),
DPAGO5_PROM_TF = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Fij B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  4
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT6_SUM_TF = ISNULL(Q.FACT,0),
FACT6_Q_TF = ISNULL(Q.FACT_Q,0),
DPAGO6_PROM_TF = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Fij B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  5
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT1_SUM_TM = ISNULL(Q.FACT,0),
FACT1_Q_TM = ISNULL(Q.FACT_Q,0),
DPAGO1_PROM_TM = DPAGO,
DPAGO1_MAX_TM = DPAGO_MAX
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) <= 30 
           AND Fecha_Pago_1 IS NULL THEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) 
           WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO,
           MAX(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) <= 30 AND Fecha_Pago_1 IS NULL THEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) 
           WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END) AS DPAGO_MAX
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN  cobra.dbo.Riesgo_ScoreConv_Fact_Mov B			
           ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) = 0
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			
ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT2_SUM_TM = ISNULL(Q.FACT,0),
FACT2_Q_TM = ISNULL(Q.FACT_Q,0),
DPAGO2_PROM_TM = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Mov B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) = 1
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT3_SUM_TM = ISNULL(Q.FACT,0),
FACT3_Q_TM = ISNULL(Q.FACT_Q,0),
DPAGO3_PROM_TM = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Mov B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) = 2
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT4_SUM_TM = ISNULL(Q.FACT,0),
FACT4_Q_TM = ISNULL(Q.FACT_Q,0),
DPAGO4_PROM_TM = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Mov B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) = 3 
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT5_SUM_TM = ISNULL(Q.FACT,0),
FACT5_Q_TM = ISNULL(Q.FACT_Q,0),
DPAGO5_PROM_TM = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Mov B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) = 4
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT6_SUM_TM = ISNULL(Q.FACT,0),
FACT6_Q_TM = ISNULL(Q.FACT_Q,0),
DPAGO6_PROM_TM = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Mov B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  5
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT1_SUM_CABLE = ISNULL(Q.FACT,0),
FACT1_Q_CABLE = ISNULL(Q.FACT_Q,0),
DPAGO1_PROM_CABLE = DPAGO,
DPAGO1_MAX_CABLE = DPAGO_MAX
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) <= 30 
           AND Fecha_Pago_1 IS NULL THEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) 
           WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO,
           MAX(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) <= 30 AND Fecha_Pago_1 IS NULL THEN DATEDIFF(DAY,Fecha_Vencimiento_1,GETDATE()) 
           WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END) AS DPAGO_MAX
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN  cobra.dbo.Riesgo_ScoreConv_Fact_Tmm B			
           ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) = 0
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			
ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT2_SUM_CABLE = ISNULL(Q.FACT,0),
FACT2_Q_CABLE = ISNULL(Q.FACT_Q,0),
DPAGO2_PROM_CABLE = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Tmm B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  1
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT3_SUM_CABLE = ISNULL(Q.FACT,0),
FACT3_Q_CABLE = ISNULL(Q.FACT_Q,0),
DPAGO3_PROM_CABLE = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Tmm B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  2
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT4_SUM_CABLE = ISNULL(Q.FACT,0),
FACT4_Q_CABLE = ISNULL(Q.FACT_Q,0),
DPAGO4_PROM_CABLE = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Tmm B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  3 
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT5_SUM_CABLE = ISNULL(Q.FACT,0),
FACT5_Q_CABLE = ISNULL(Q.FACT_Q,0),
DPAGO5_PROM_CABLE = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Tmm B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  4
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET 
FACT6_SUM_CABLE = ISNULL(Q.FACT,0),
FACT6_Q_CABLE = ISNULL(Q.FACT_Q,0),
DPAGO6_PROM_CABLE = DPAGO
FROM cobra.dbo.Riesgo_ScoreConv P
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15) AS DOC, SUM(B.Total_Facturado_1) AS FACT, COUNT(B.Total_Facturado_1) AS FACT_Q,
           ROUND(AVG(CASE WHEN DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) > 90 OR Fecha_Pago_1 IS NULL THEN 90 ELSE DATEDIFF(DAY,Fecha_Vencimiento_1,Fecha_Pago_1) END),0) AS DPAGO
           FROM (SELECT DISTINCT NRO_IDENTIFICACION, COD_CLIENTE FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm) A
           INNER JOIN cobra.dbo.Riesgo_ScoreConv_Fact_Tmm B			ON RIGHT('0000000000000'+A.COD_CLIENTE,13) = RIGHT('0000000000000'+B.Cliente,13) AND DATEDIFF(MONTH,Fecha_Vencimiento_1,GETDATE()) =  5
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(A.NRO_IDENTIFICACION)),15)) Q			ON P.DOC = Q.DOC





ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
CONT1_TF INT,
CONT1_TM INT,
CONT_ULT1M INT


UPDATE cobra.dbo.Riesgo_ScoreConv
SET
CONT1_TF = ISNULL(B.CONT1,0)
FROM cobra.dbo.Riesgo_ScoreConv A
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(nro_identificacion)),15) AS DOC, SUM(Contactos_fij) AS CONT1
           FROM cobra.dbo.Riesgo_ScoreConv_Contactos_Fij_Mov_Tmmm
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(nro_identificacion)),15)) B		ON A.DOC = B.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET
CONT1_TM = ISNULL(B.CONT1,0)
FROM cobra.dbo.Riesgo_ScoreConv A
LEFT JOIN (SELECT RIGHT('000000000000000'+LTRIM(RTRIM(nro_identificacion)),15) AS DOC, SUM(Contactos_mov) AS CONT1
           FROM cobra.dbo.Riesgo_ScoreConv_Contactos_Fij_Mov_Tmmm
           GROUP BY RIGHT('000000000000000'+LTRIM(RTRIM(nro_identificacion)),15)) B		ON A.DOC = B.DOC


UPDATE cobra.dbo.Riesgo_ScoreConv
SET
CONT_ULT1M = CONT1_TF + CONT1_TM
FROM cobra.dbo.Riesgo_ScoreConv A


ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
FACT1_SUM NUMERIC(15,2),
FACT2_SUM NUMERIC(15,2),
FACT3_SUM NUMERIC(15,2),
FACT4_SUM NUMERIC(15,2),
FACT5_SUM NUMERIC(15,2),
FACT6_SUM NUMERIC(15,2),
INDF1 SMALLINT,
INDF2 SMALLINT,
INDF3 SMALLINT,
INDF4 SMALLINT,
INDF5 SMALLINT,
INDF6 SMALLINT


UPDATE cobra.dbo.Riesgo_ScoreConv
SET
FACT1_SUM = FACT1_SUM_TF + FACT1_SUM_TM + FACT1_SUM_CABLE,
FACT2_SUM = FACT2_SUM_TF + FACT2_SUM_TM + FACT2_SUM_CABLE,
FACT3_SUM = FACT3_SUM_TF + FACT3_SUM_TM + FACT3_SUM_CABLE,
FACT4_SUM = FACT4_SUM_TF + FACT4_SUM_TM + FACT4_SUM_CABLE,
FACT5_SUM = FACT5_SUM_TF + FACT5_SUM_TM + FACT5_SUM_CABLE,
FACT6_SUM = FACT6_SUM_TF + FACT6_SUM_TM + FACT6_SUM_CABLE,
INDF1 = CASE WHEN FACT1_Q_TF + FACT1_Q_TM + FACT1_Q_CABLE > 0 THEN 1 ELSE 0 END, 
INDF2 = CASE WHEN FACT2_Q_TF + FACT2_Q_TM + FACT2_Q_CABLE > 0 THEN 1 ELSE 0 END, 
INDF3 = CASE WHEN FACT3_Q_TF + FACT3_Q_TM + FACT3_Q_CABLE > 0 THEN 1 ELSE 0 END, 
INDF4 = CASE WHEN FACT4_Q_TF + FACT4_Q_TM + FACT4_Q_CABLE > 0 THEN 1 ELSE 0 END, 
INDF5 = CASE WHEN FACT5_Q_TF + FACT5_Q_TM + FACT5_Q_CABLE > 0 THEN 1 ELSE 0 END, 
INDF6 = CASE WHEN FACT6_Q_TF + FACT6_Q_TM + FACT6_Q_CABLE > 0 THEN 1 ELSE 0 END
FROM cobra.dbo.Riesgo_ScoreConv


ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
DPAGO1_PROM NUMERIC(15,2),
DPAGO2_PROM NUMERIC(15,2),
DPAGO3_PROM NUMERIC(15,2),
DPAGO4_PROM NUMERIC(15,2),
DPAGO5_PROM NUMERIC(15,2),
DPAGO6_PROM NUMERIC(15,2),
DPAGO1_MAX NUMERIC(15,2)


UPDATE cobra.dbo.Riesgo_ScoreConv
SET
DPAGO1_PROM = CASE WHEN (CASE WHEN DPAGO1_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO1_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO1_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END) = 0 THEN -99 
                   ELSE ROUND((ISNULL(DPAGO1_PROM_TF,0) + ISNULL(DPAGO1_PROM_TM,0) + ISNULL(DPAGO1_PROM_CABLE,0)) / (CASE WHEN DPAGO1_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO1_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO1_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END),2) END,
DPAGO2_PROM = CASE WHEN (CASE WHEN DPAGO2_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO2_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO2_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END) = 0 THEN -99 
                   ELSE ROUND((ISNULL(DPAGO2_PROM_TF,0) + ISNULL(DPAGO2_PROM_TM,0) + ISNULL(DPAGO2_PROM_CABLE,0)) / (CASE WHEN DPAGO2_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO2_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO2_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END),2) END,
DPAGO3_PROM = CASE WHEN (CASE WHEN DPAGO3_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO3_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO3_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END) = 0 THEN -99 
                   ELSE ROUND((ISNULL(DPAGO3_PROM_TF,0) + ISNULL(DPAGO3_PROM_TM,0) + ISNULL(DPAGO3_PROM_CABLE,0)) / (CASE WHEN DPAGO3_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO3_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO3_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END),2) END,
DPAGO4_PROM = CASE WHEN (CASE WHEN DPAGO4_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO4_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO4_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END) = 0 THEN -99 
                   ELSE ROUND((ISNULL(DPAGO4_PROM_TF,0) + ISNULL(DPAGO4_PROM_TM,0) + ISNULL(DPAGO4_PROM_CABLE,0)) / (CASE WHEN DPAGO4_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO4_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO4_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END),2) END,
DPAGO5_PROM = CASE WHEN (CASE WHEN DPAGO5_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO5_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO5_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END) = 0 THEN -99 
                   ELSE ROUND((ISNULL(DPAGO5_PROM_TF,0) + ISNULL(DPAGO5_PROM_TM,0) + ISNULL(DPAGO5_PROM_CABLE,0)) / (CASE WHEN DPAGO5_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO5_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO5_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END),2) END,
DPAGO6_PROM = CASE WHEN (CASE WHEN DPAGO6_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO6_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO6_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END) = 0 THEN -99 
                   ELSE ROUND((ISNULL(DPAGO6_PROM_TF,0) + ISNULL(DPAGO6_PROM_TM,0) + ISNULL(DPAGO6_PROM_CABLE,0)) / (CASE WHEN DPAGO6_PROM_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO6_PROM_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO6_PROM_CABLE IS NOT NULL THEN 1 ELSE 0 END),2) END,                                                                           
DPAGO1_MAX = CASE WHEN (CASE WHEN DPAGO1_MAX_TF IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO1_MAX_TM IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN DPAGO1_MAX_CABLE IS NOT NULL THEN 1 ELSE 0 END) = 0 THEN -99
                  ELSE CASE WHEN ISNULL(DPAGO1_MAX_TF,-99) >= ISNULL(DPAGO1_MAX_TM,-99) AND ISNULL(DPAGO1_MAX_TF,-99) >= ISNULL(DPAGO1_MAX_CABLE,-99) THEN ISNULL(DPAGO1_MAX_TF,-99)
                            WHEN ISNULL(DPAGO1_MAX_TM,-99) >= ISNULL(DPAGO1_MAX_TF,-99) AND ISNULL(DPAGO1_MAX_TM,-99) >= ISNULL(DPAGO1_MAX_CABLE,-99) THEN ISNULL(DPAGO1_MAX_TM,-99) 
                            ELSE ISNULL(DPAGO1_MAX_CABLE,-99) END END                                                                          
FROM cobra.dbo.Riesgo_ScoreConv


ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
DPAGO_PROM_ULT6M INT,
DPAGO_PROM_ULT3M INT,
FACT_PEND_ULT6M NUMERIC(15,2)


UPDATE cobra.dbo.Riesgo_ScoreConv
SET
DPAGO_PROM_ULT6M = CASE WHEN ((CASE WHEN DPAGO1_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO2_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO3_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO4_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO5_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO6_PROM = -99 THEN 0 ELSE 1 END)) = 0 THEN -99 
                        ELSE
                         ((CASE WHEN DPAGO1_PROM = -99 THEN 0 ELSE 1 END)*DPAGO1_PROM + (CASE WHEN DPAGO2_PROM = -99 THEN 0 ELSE 1 END)*DPAGO2_PROM + (CASE WHEN DPAGO3_PROM = -99 THEN 0 ELSE 1 END)*DPAGO3_PROM + (CASE WHEN DPAGO4_PROM = -99 THEN 0 ELSE 1 END)*DPAGO4_PROM + (CASE WHEN DPAGO5_PROM = -99 THEN 0 ELSE 1 END)*DPAGO5_PROM + (CASE WHEN DPAGO6_PROM = -99 THEN 0 ELSE 1 END)*DPAGO6_PROM) / 
                         ((CASE WHEN DPAGO1_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO2_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO3_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO4_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO5_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO6_PROM = -99 THEN 0 ELSE 1 END)) END,
DPAGO_PROM_ULT3M = CASE WHEN ((CASE WHEN DPAGO1_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO2_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO3_PROM = -99 THEN 0 ELSE 1 END)) = 0 THEN -99 
                        ELSE
                         ((CASE WHEN DPAGO1_PROM = -99 THEN 0 ELSE 1 END)*DPAGO1_PROM + (CASE WHEN DPAGO2_PROM = -99 THEN 0 ELSE 1 END)*DPAGO2_PROM + (CASE WHEN DPAGO3_PROM = -99 THEN 0 ELSE 1 END)*DPAGO3_PROM) / 
                         ((CASE WHEN DPAGO1_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO2_PROM = -99 THEN 0 ELSE 1 END) + (CASE WHEN DPAGO3_PROM = -99 THEN 0 ELSE 1 END)) END               
FROM cobra.dbo.Riesgo_ScoreConv


UPDATE cobra.dbo.Riesgo_ScoreConv
SET
FACT_PEND_ULT6M = (5*INDF1*FACT1_SUM + 3*INDF2*FACT2_SUM + INDF3*FACT3_SUM - INDF4*FACT4_SUM - 3*INDF5*FACT5_SUM - 5*INDF6*FACT6_SUM) / 35.0
FROM cobra.dbo.Riesgo_ScoreConv


ALTER TABLE cobra.dbo.Riesgo_ScoreConv
ADD
V_1 VARCHAR(2),
V_2 VARCHAR(2),
V_3 VARCHAR(2),
V_4 VARCHAR(2),
V_5 VARCHAR(2),
V_6 VARCHAR(2),
PROB decimal (10,6),
GRUPO VARCHAR(3),
COD_CONVERGENCIA tinyint NULL


UPDATE cobra.dbo.Riesgo_ScoreConv
SET V_1 = CASE WHEN ANTIG >= 0 AND ANTIG <= 11 THEN '1'
               WHEN ANTIG >= 12 AND ANTIG <= 21 THEN '2'
               WHEN ANTIG >= 22 AND ANTIG <= 31 THEN '3'
               WHEN ANTIG >= 32 AND ANTIG <= 48 THEN '4'
               WHEN ANTIG >= 49 AND ANTIG <= 84 THEN '5'
               WHEN ANTIG >= 85 THEN '6'
               ELSE '99' END
FROM cobra.dbo.Riesgo_ScoreConv


UPDATE cobra.dbo.Riesgo_ScoreConv
SET V_2 = CASE WHEN DPAGO1_MAX = -99 THEN '3'
               WHEN DPAGO1_MAX <= 21 THEN '1'
               WHEN DPAGO1_MAX <= 64 THEN '2'
               WHEN DPAGO1_MAX > 64 THEN '4'
               ELSE '99' END
FROM cobra.dbo.Riesgo_ScoreConv


UPDATE cobra.dbo.Riesgo_ScoreConv
SET V_3 = CASE WHEN FACT_PEND_ULT6M <= -7.57 OR FACT_PEND_ULT6M > 14.24 OR INDF1 + INDF2 + INDF3 + INDF4 + INDF5 + INDF6 <= 1 THEN '1'
               WHEN (FACT_PEND_ULT6M > -7.57 AND FACT_PEND_ULT6M <= -1.915) OR (FACT_PEND_ULT6M > 3.969 AND FACT_PEND_ULT6M <= 14.24) THEN '2'
               WHEN FACT_PEND_ULT6M > 1.423 AND FACT_PEND_ULT6M <= 3.969 THEN '3'
               WHEN (FACT_PEND_ULT6M > -1.915 AND FACT_PEND_ULT6M <= -0.216) OR (FACT_PEND_ULT6M >= 0 AND FACT_PEND_ULT6M <= 1.423) THEN '4'
               WHEN FACT_PEND_ULT6M > -0.216 AND FACT_PEND_ULT6M < 0 THEN '5'
               ELSE '99' END
FROM cobra.dbo.Riesgo_ScoreConv


UPDATE cobra.dbo.Riesgo_ScoreConv
SET V_4 = CASE WHEN CONT_ULT1M = 0 THEN '1'
               WHEN CONT_ULT1M >= 1 THEN '2'
               ELSE '99' END
FROM cobra.dbo.Riesgo_ScoreConv


UPDATE cobra.dbo.Riesgo_ScoreConv
SET V_5 = CASE WHEN DPAGO_PROM_ULT3M <= 0 AND DPAGO_PROM_ULT3M <> -99 THEN '1'
               WHEN DPAGO_PROM_ULT3M <= 2 AND DPAGO_PROM_ULT3M <> -99 THEN '2'
               WHEN DPAGO_PROM_ULT3M <= 4 AND DPAGO_PROM_ULT3M <> -99 THEN '3'
               WHEN DPAGO_PROM_ULT3M <= 6 AND DPAGO_PROM_ULT3M <> -99 THEN '4'
               WHEN DPAGO_PROM_ULT3M <= 11 OR DPAGO_PROM_ULT3M = -99 THEN '5'
               WHEN DPAGO_PROM_ULT3M <= 37 THEN '6'
               WHEN DPAGO_PROM_ULT3M > 37 THEN '7'
               ELSE '99' END
FROM cobra.dbo.Riesgo_ScoreConv


UPDATE cobra.dbo.Riesgo_ScoreConv
SET V_6 = CASE WHEN DPAGO_PROM_ULT6M <= -1 AND DPAGO_PROM_ULT6M <> -99 THEN '1'
               WHEN DPAGO_PROM_ULT6M <= 0 AND DPAGO_PROM_ULT6M <> -99 THEN '2'
               WHEN DPAGO_PROM_ULT6M <= 2 AND DPAGO_PROM_ULT6M <> -99 THEN '3'
               WHEN DPAGO_PROM_ULT6M <= 4 AND DPAGO_PROM_ULT6M <> -99 THEN '4'
               WHEN DPAGO_PROM_ULT6M <= 7 AND DPAGO_PROM_ULT6M <> -99 THEN '5'
               WHEN DPAGO_PROM_ULT6M <= 18 OR DPAGO_PROM_ULT6M = -99 THEN '6'
               WHEN DPAGO_PROM_ULT6M <= 33 THEN '7'
               WHEN DPAGO_PROM_ULT6M > 33 THEN '8'
               ELSE '99' END
FROM cobra.dbo.Riesgo_ScoreConv


UPDATE cobra.dbo.Riesgo_ScoreConv
SET PROB = ROUND(1/(1+EXP(-1*(-0.2444 + 
           CASE WHEN V_1 = '1' THEN -0.5414 WHEN V_1 = '2' THEN -0.4347 WHEN V_1 = '3' THEN -0.2482 WHEN V_1 = '4' THEN -0.1966 WHEN V_1 = '5' THEN -0.1268
                WHEN V_1 = '6' THEN 0 END + 
           CASE WHEN V_2 = '1' THEN 1.572 WHEN V_2 = '2' THEN 1.141 WHEN V_2 = '3' THEN 0.8873 WHEN V_2 = '4' THEN 0 END +
           CASE WHEN V_3 = '1' THEN -0.5152 WHEN V_3 = '2' THEN -0.3666 WHEN V_3 = '3' THEN -0.2018 WHEN V_3 = '4' THEN -0.1092 WHEN V_3 = '5' THEN 0 END +
           CASE WHEN V_4 = '1' THEN 0.1234 WHEN V_4 = '2' THEN 0 END +
           CASE WHEN V_5 = '1' THEN 0.9077 WHEN V_5 = '2' THEN 0.7999 WHEN V_5 = '3' THEN 0.68 WHEN V_5 = '4' THEN 0.5849 WHEN V_5 = '5' THEN 0.5683
                WHEN V_5 = '6' THEN 0.2199 WHEN V_5 = '7' THEN 0 END +
           CASE WHEN V_6 = '1' THEN 2.246 WHEN V_6 = '2' THEN 1.946 WHEN V_6 = '3' THEN 1.654 WHEN V_6 = '4' THEN 1.454 WHEN V_6 = '5' THEN 1.229
                WHEN V_6 = '6' THEN 1.098 WHEN V_6 = '7' THEN 0.5513 WHEN V_6 = '8' THEN 0 END))),6) 
FROM cobra.dbo.Riesgo_ScoreConv



--SELECT * FROM LUNA.MASTER_LUNA
--SELECT * FROM LUNA.CORE_CONVERGENCIA
--SELECT count(0) FROM cobra.dbo.Riesgo_ScoreConv  --6,372,041

-- actualiza convergencia --23-01-2017
UPDATE cobra.dbo.Riesgo_ScoreConv SET
COD_CONVERGENCIA=B.COD_CONVERGENCIA
FROM cobra.dbo.Riesgo_ScoreConv A INNER JOIN LUNA.MASTER_LUNA B
ON a.TIP_DOC=b.COD_TIPO_IDENTIFICACION  and a.NRO_IDENTIFICACION_ORIGEN=b.NRO_IDENTIFICACION


--- MODELO ANTERIOR
--UPDATE cobra.dbo.Riesgo_ScoreConv
--SET GRUPO = CASE WHEN PROB >= 0.96573106 THEN '1'
--                 WHEN PROB >= 0.92600877 THEN '2'
--                 WHEN PROB >= 0.82564713 THEN '3'
--                 WHEN PROB >= 0.75110464 THEN '4'
--                 WHEN PROB >= 0.53074909 THEN '5'
--                 WHEN PROB < 0.53074909 AND PROB >= 0 THEN '6'
--                 ELSE '99' END
--FROM cobra.dbo.Riesgo_ScoreConv

--UPDATE cobra.dbo.Riesgo_ScoreConv SET
--GRUPO=0

-----Fija/Movil  (23-01-2017)  select * from cobra.dbo.Riesgo_ScoreConv
--UPDATE cobra.dbo.Riesgo_ScoreConv
--SET GRUPO = CASE WHEN PROB >= 0.94 and COD_CONVERGENCIA in (1,2,4,5,7,8,9,10) THEN '1'					-- fija
--                 WHEN PROB >= 0.8 and PROB < 0.94 AND COD_CONVERGENCIA in (1,2,4,5,7,8,9,10) THEN '2'   -- fija
--                 WHEN PROB > 0 AND PROB < 0.8 and COD_CONVERGENCIA in (1,2,4,5,7,8,9,10) THEN '3'       -- fija
--                 WHEN PROB >= 0.95 and COD_CONVERGENCIA in (3,6) THEN '1'								-- movil
--                 WHEN PROB >= 0.93 AND PROB < 0.95  and COD_CONVERGENCIA in (3,6)  THEN '2'				-- movil
--                 WHEN PROB > 0 AND PROB < 0.93  and COD_CONVERGENCIA in (3,6)  THEN '3'				    -- movil
--                 ELSE '0' END
--FROM cobra.dbo.Riesgo_ScoreConv


---Fija/Movil  (03-05-2017)  select * from cobra.dbo.Riesgo_ScoreConv
UPDATE cobra.dbo.Riesgo_ScoreConv
SET GRUPO = CASE WHEN PROB >= 0.9491 and COD_CONVERGENCIA in (1,2,4,5,7,8,9,10) THEN '1'					-- fija
                 WHEN PROB >= 0.8 and PROB < 0.9491 AND COD_CONVERGENCIA in (1,2,4,5,7,8,9,10) THEN '2'		-- fija
                 WHEN PROB > 0 AND PROB < 0.8 and COD_CONVERGENCIA in (1,2,4,5,7,8,9,10) THEN '3'			-- fija
                 WHEN PROB >= 0.9551 and COD_CONVERGENCIA in (3,6) THEN '1'									-- movil
                 WHEN PROB >= 0.93 AND PROB < 0.9551  and COD_CONVERGENCIA in (3,6)  THEN '2'				-- movil
                 WHEN PROB > 0 AND PROB < 0.93  and COD_CONVERGENCIA in (3,6)  THEN '3'						-- movil
                 ELSE '0' END
FROM cobra.dbo.Riesgo_ScoreConv


--cobra.dbo.Riesgo_ScoreConv_Grupos_PRUEBA

--select grupo, COUNT(0) from cobra.dbo.Riesgo_ScoreConv_Grupos
--group by grupo

--grupo	cantidad	
--0		44,205 	1%
--1	 2,406,060 	50%
--2	 1,349,131 	28%
--3	   983,222 	21%
--	 4,782,618 	100%


--select * into  SRMS.dbo.Riesgo_ScoreConv_03052017 from cobra.dbo.Riesgo_ScoreConv --6,168,673
--select * from  cobra.dbo.Riesgo_ScoreConv
--select * into  SRMS.dbo.Riesgo_ScoreConv_23012017 from cobra.dbo.Riesgo_ScoreConv  --6,372,041

If OBJECT_ID('cobra.dbo.Riesgo_ScoreConv_Grupos') Is Not Null Drop table  cobra.dbo.Riesgo_ScoreConv_Grupos
--drop table cobra.dbo.Riesgo_ScoreConv_Grupos

--SELECT * FROM  cobra.dbo.Riesgo_ScoreConv_Grupos

--ALTER TABLE cobra.dbo.Riesgo_ScoreConv
--ADD NRO_IDENTIFICACION_ORIGEN VARCHAR (50)

--SELECT  DOC, GRUPO,TIP_DOC,NRO_IDENTIFICACION_ORIGEN
--INTO cobra.dbo.Riesgo_ScoreConv_Grupos
--FROM cobra.dbo.Riesgo_ScoreConv
--WHERE ANTIG >= 6 AND INDF1 + INDF2 + INDF3 + INDF4 + INDF5 + INDF6 >= 3

--SE AÑADIÓ EL 06-12-2016.
SELECT   DOC, GRUPO,TIP_DOC,NRO_IDENTIFICACION_ORIGEN
INTO cobra.dbo.Riesgo_ScoreConv_Grupos
FROM cobra.dbo.Riesgo_ScoreConv
WHERE INDF1 + INDF2 + INDF3 + INDF4 + INDF5 + INDF6 >= 3


--/* AÑADIR */
--DROP TABLE cobra.dbo.Riesgo_ScoreConv_Grupos2
--DROP TABLE cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm2 

--SELECT TIP_DOC, DOC, GRUPO
--INTO cobra.dbo.Riesgo_ScoreConv_Grupos2
--FROM cobra.dbo.Riesgo_ScoreConv
--WHERE ANTIG >= 6 AND INDF1 + INDF2 + INDF3 + INDF4 + INDF5 + INDF6 >= 3

--ALTER TABLE cobra.dbo.Riesgo_ScoreConv_Grupos2
--ADD DOC2 VARCHAR (50)

----SELECT * FROM cobra.dbo.Riesgo_ScoreConv_Grupos2					 --4,768,173
-------- 

--SELECT  COD_TIPO_IDENTIFICACION, NRO_IDENTIFICACION 
--INTO cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm2 
--FROM Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm

--ALTER TABLE   cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm2
--ADD NRO_IDENTIFICACION2 VARCHAR (15)

--UPDATE cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm2 SET   -- 10 MINUTOS
--NRO_IDENTIFICACION2=RIGHT('000000000000000'+LTRIM(RTRIM(NRO_IDENTIFICACION)),15)

----SELECT * FROM cobra.dbo.Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm2		 --4,768,173
------- 

--UPDATE cobra.dbo.Riesgo_ScoreConv_Grupos SET
--NRO_IDENTIFICACION_ORIGEN=B.NRO_IDENTIFICACION
--FROM cobra.dbo.Riesgo_ScoreConv_Grupos A INNER JOIN Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm2 B
--ON A.DOC=B.NRO_IDENTIFICACION2 AND A.TIP_DOC=B.COD_TIPO_IDENTIFICACION

--SELECT TOP 1* FROM Riesgo_ScoreConv_Grupos
--SELECT TOP 1* FROM Riesgo_ScoreConv_Plantas_Fij_Mov_Tmmm2






----***************************************  [EXPORTAR PLANTAS ] ********************************------

Declare     @query8 as varchar(1000)
SET @query8 = 'bcp "select * from COBRA.dbo.Riesgo_ScoreConv_Grupos"   QUERYOUT "\\gppesplcli1212\Servidor_FACO\Operaciones\DESA\GESTORES\MOVIL\Pagos\HOY\Riesgo_ScoreConv_Grupos.txt"  -c -t^| -T -P' 
 EXEC master..xp_cmdshell @query8
 
 
Declare     @query9 as varchar(1000)
SET @query9 = 'bcp "select * from COBRA.dbo.Riesgo_ScoreConv"   QUERYOUT "\\gppesplcli1212\Servidor_FACO\Operaciones\DESA\GESTORES\MOVIL\Pagos\HOY\Riesgo_ScoreConv_sin_filtro.txt"  -c -t^| -T -P' 
 EXEC master..xp_cmdshell @query9


END