-- DROP TABLE DIN_PARAMETRO;

CREATE TABLE DIN_PARAMETRO(
	PARAMETRO_ID INT NOT NULL IDENTITY(1, 1), 
	CODIGO VARCHAR(4) NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	DESCRIPCION VARCHAR(250) NOT NULL,
	VALOR VARCHAR(50) NOT NULL, 
	VALOR2 VARCHAR(50) NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL, 
	FECHA_CREACION DATETIME NOT NULL, 
	USUARIO_MODIFICA VARCHAR(50) NULL, 
	FECHA_MODIFICA DATETIME NULL
);

ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT PK_PARAMETRO PRIMARY KEY(PARAMETRO_ID);

ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT DF_PARAMETRO_CODIGO DEFAULT '' FOR CODIGO;
ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT DF_PARAMETRO_NOMBRE DEFAULT '' FOR NOMBRE;
ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT DF_PARAMETRO_DESCRIPCION DEFAULT '' FOR DESCRIPCION;
ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT DF_PARAMETRO_VALOR DEFAULT '' FOR VALOR;
ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT DF_PARAMETRO_VALOR2 DEFAULT '' FOR VALOR2;
ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT DF_PARAMETRO_USUARIO_CREACION DEFAULT '' FOR USUARIO_CREACION;

ALTER TABLE DIN_PARAMETRO ADD CONSTRAINT UQ_PARAMETRO_CODIGO UNIQUE(CODIGO);

